apiVersion: v1
kind: Pod
metadata:
  name: azureiothub
  labels:
    purpose: azure-iot-hub
spec:
  containers:
  - name: azureiothub
    image: eu.gcr.io/camp2019-past/azureiothub:1.0
    env:
    - name: deviceId
      value: "Device002"
